export default [
  {
    id: 1,
    name: 'Pasig - Common',
    age: 20,
    country: 'pasig',
    price: '0.54 ETH',
    src: '/assets/images/girl-1.png',
  },
  {
    id: 2,
    name: 'Isabela - Common',
    age: 31,
    country: 'isabela',
    price: '0.31 ETH',
    src: '/assets/images/girl-2.png',
  },
  {
    id: 3,
    name: 'Davao Del Sur - Common',
    age: 22,
    country: 'colombia',
    price: '0.12 ETH',
    src: '/assets/images/girl-3.png',
  },
  {
    id: 4,
    name: 'ABERMakati - Uncommon',
    age: 23,
    country: 'thailand',
    price: '0.22 ETH',
    src: '/assets/images/girl-4.png',
  },
  {
    id: 5,
    name: 'Iloilo City - Common',
    age: 24,
    country: 'china',
    price: '0.2 ETH',
    src: '/assets/images/girl-5.png',
  },
  {
    id: 6,
    name: 'Masbate - Common',
    age: 25,
    country: 'vietnam',
    price: '0.15 ETH',
    src: '/assets/images/girl-6.png',
  },
  {
    id: 7,
    name: 'Cavite - Common',
    age: 28,
    country: 'korea',
    price: '0.15 ETH',
    src: '/assets/images/girl-7.png',
  },
  {
    id: 8,
    name: 'Mandaluyong - Uncommon',
    age: 23,
    country: 'hongkong',
    price: '0.32 ETH',
    src: '/assets/images/girl-8.png',
  },
  {
    id: 9,
    name: 'Cavite - Common',
    age: 28,
    country: 'campuchia',
    price: '0.321 ETH',
    src: '/assets/images/girl-9.png',
  },
  {
    id: 10,
    name: 'Albay - Common',
    age: 28,
    country: 'japan',
    price: '0.32 ETH',
    src: '/assets/images/girl-10.png',
  },
];
